### ISSUE TITLE
Motor Torque

### ISSUE THREAD

**Issue by BrightKnight02** [darint916/ros2-gazebo-drake-sims#11]
For `parse_data` in `cost_update.py`, `instant_power` is not calculated correctly. This calculation requires the torque applied to the wing at a moment in time and the stroke angular velocity at that same moment.

**Comment by BrightKnight02** [comment]
need the angular velocity of the stroke joint and the torque applied to the stroke joint by the motor.

**Comment by BrightKnight02** [comment]
This requires an update to line 63 of `cost_update` to included the required data rather than the dummy calculation.

**Comment by BrightKnight02** [comment]
Actually thinking in retrospect rather than using the motor output power we should probably use the electrical input power to the motor. Still need all the same information, it just changes how power is calculated in the cost function.

**Comment by darint916** [comment]
Rewrote with voltage * current,
