### ISSUE TITLE
Inertia Tensor needs to be about center of mass

### ISSUE THREAD

**Issue by BrightKnight02** [darint916/ros2-gazebo-drake-sims#17]
According to [this](http://sdformat.org/spec?elem=link), the inertia tensor for the a link in the sdf needs to be about the center of mass of the link. Since the current tensor is calculated about the wing root, the calculated tensor needs to be manipulated according to the [parallel axis theorem](https://en.wikipedia.org/wiki/Parallel_axis_theorem).

**Comment by BrightKnight02** [comment]
Fixed (probably) with https://github.com/darint916/ros2-gazebo-drake-sims/pull/18

**Comment by darint916** [comment]
Inertia not passing newly written inertia, nailing down error by testing all inertia functions. Matching against Solidworks assembly source of truth values. Testing #15

**Comment by BrightKnight02** [comment]
Potentially solved with #19

**Comment by darint916** [comment]
Requested new changes, follow PR. Performed smoke test on autogenerated values (Failed)

**Comment by BrightKnight02** [comment]
When generating the iteration, the SDF file needs to have the location of the wing center of mass
